version: "3.6"

services:
  georgecolgrove:
    build: ./websites/personalwebsite
    volumes: 
      - ./websites/personalwebsite/www:/var/www/site
      - ./websites/personalwebsite/config:/etc/apache2/sites-enabled/
      - ./websites/personalwebsite/logs:/var/log/apache2
    env_file:
      - nginx.env  
    networks: 
      - frontend
<<<<<<< HEAD
  ritcampus:
    image: php:7-apache
    volumes:
      - ./websites/ritcampus:/var/www/html:rw
    networks: 
      - frontend
  gwcprojects:
    image: php:7-apache
    volumes:
      - ./websites/website:/var/www/html:rw
    networks: 
      - frontend
=======
>>>>>>> 0921ffcfa6445f38ed7b329ff3ec794492d7a3bd
  nginx:
    build: ./proxy
    ports:
      - 80:80
      - 443:443
    networks: 
      - frontend
    depends_on:
      - georgecolgrove
# Do not forget to 'docker network create georgecolgrove' before launch
networks: 
  frontend:
