version: "3.6"

services:
  georgecolgrove:
    build: ./websites/personalwebsite
    volumes: 
      - ./websites/personalwebsite/www:/var/www/html/
      - ./websites/personalwebsite/config:/etc/apache2/sites-enabled/
      - ./websites/personalwebsite/logs:/var/log/apache2
    env_file:
      - nginx.env  
    networks: 
      - frontend
  angular-georgecolgrove-client:
    image: 'captainglacier/angular-georgecolgrove:latest'
    volumes:
      - ./websites/angular/logs/:/logs
    networks: 
      - frontend
  ritcampus:
    image: "php:7-apache"
    volumes:
      - ./websites/ritcampus:/var/www/html:rw
    networks: 
      - frontend
  gwcprojects:
    image: php:7-apache
    volumes:
      - ./websites/website:/var/www/html:rw
    networks: 
      - frontend
  nginx:
    build: ./proxy
    ports:
      - 80:80
      - 443:443
    networks: 
      - frontend
    volumes: 
      - ./proxy/logs:/logs
      - ./proxy/certs:/etc/ssl/certs/nginx
      - ./proxy/letsencrypt/:/var/www/html
    depends_on:
      - georgecolgrove
      - ritcampus
      - gwcprojects
      - angular-georgecolgrove-client
      - db1
  db1:
    image: "mysql:8.0"
    ports:
      - localhost:3306:3306
    networks: 
      - backend
    volumes:
      - ./databases/db1:/var/lib/mysql
  db2:
    image: 11-postgres
    ports:
      - localhost:5432:5432
    volumes:
      - ./databases/db2:/var/lib/postgresql/data
    restart: always


# Do not forget to 'docker network create georgecolgrove' before launch
networks: 
  frontend:
  backend:
