version: "3.6"

services:
  php-georgecolgrove:
    image: captainglacier/old-php-georgecolgrove:latest
    volumes:
      - ./logs/php-georgecolgrove:/var/log/apache2
    networks: 
      - frontend
    restart: always
  angular-georgecolgrove:
    image: captainglacier/angular-georgecolgrove:latest
    networks: 
      - frontend
    restart: always
    environment:
      - PORT=80
  angular-georgecolgrove-beta:
    image: captainglacier/angular-georgecolgrove:beta
    networks:
    - frontend
    restart: always
    environment:
      - PORT=80
  cdn-georgecolgrove:
    image: captainglacier/simple-docker-cdn:latest
    volumes:
      - ./logs/cdn-georgecolgrove/:/logs
      - ./cdn/georgecolgrove/:/var/www/assets
    networks: 
      - frontend
    restart: always
  ritcampus:
    image: "php:7-apache"
    volumes:
      - ./websites/ritcampus:/var/www/html:rw
    networks: 
      - frontend
  gwcprojects:
    image: php:7-apache
    volumes:
      - ./websites/website:/var/www/html:rw
    networks: 
      - frontend
  nginx:
    image: nginx:1-alpine
    ports:
      - 80:80
      - 443:443
    networks: 
      - frontend
    volumes: 
      - ./logs/nginx:/var/logs/nginx/
      - /home/georgecolgrove/letsencypt/config/archive/georgecolgrove.com-0001/:/etc/ssl/certs/nginx/archive/georgecolgrove.com-0001/:ro
      - /home/georgecolgrove/letsencypt/config/live/georgecolgrove.com-0001/:/etc/ssl/certs/nginx/live/georgecolgrove.com/:ro
#      - /home/georgecolgrove/letsencypt/config/live/cert.pem:/etc/ssl/certs/nginx/cert.pem
#      - /home/georgecolgrove/letsencypt/config/live/chain.pem:/etc/ssl/certs/nginx/chain.pem
#      - /home/georgecolgrove/letsencypt/config/live/fullchain.pem:/etc/ssl/certs/nginx/fullchain.pem
#      - /home/georgecolgrove/letsencypt/config/live/privkey.pem:/etc/ssl/certs/nginx/privkey.pem
#      - ./proxy/certs:/etc/ssl/certs/nginx/
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/includes:/etc/nginx/includes/
      - ./proxy/backend-not-found.html:/var/www/html/backend-not-found.html
    depends_on:
      - php-georgecolgrove
      - angular-georgecolgrove
      - cdn-georgecolgrove
      - ritcampus
      - gwcprojects
  db1:
    image: mysql:8.0
    ports:
      - 127.0.0.1:3306:3306
    networks: 
      - backend
    volumes:
      - ./databases/db1:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  db2:
    image: postgres:16-alpine
    ports:
      - 127.0.0.1:5432:5432
    networks: 
      - backend
    volumes:
      - ./databases/db2:/var/lib/postgresql/data

networks: 
  frontend:
  backend:
