version: "3.6"

services:
  georgecolgrove:
    build: ./websites/personalwebsite
    volumes: 
      - ./websites/personalwebsite/www:/var/www/html/
      - ./websites/personalwebsite/config:/etc/apache2/sites-enabled/
      - ./websites/personalwebsite/logs:/var/log/apache2
    env_file:
      - nginx.env  
    networks: 
      - frontend
  angular-georgecolgrove-client:
    image: "httpd:2.4.33-alpine"
    volumes:
      - ./websites/angular-personalwebsite/client/dist:/usr/local/apache2/htdocs/
    networks: 
      - frontend
  ritcampus:
    image: "php:7-apache"
    volumes:
      - ./websites/ritcampus:/var/www/html:rw
    networks: 
      - frontend
  gwcprojects:
    image: php:7-apache
    volumes:
      - ./websites/website:/var/www/html:rw
    networks: 
      - frontend
  nginx:
    build: ./proxy
    ports:
      - 80:80
      - 443:443
    networks: 
      - frontend
    volumes: 
      - ./proxy/logs:/logs
      - ./proxy/certs:/etc/ssl/certs/nginx
      - ./proxy/letsencrypt/:/var/www/html
    depends_on:
      - georgecolgrove
      - ritcampus
      - gwcprojects
      - angular-georgecolgrove-client
      - database
  db1:
    image: "mysql:8.0.11"
    networks: 
      - backend
      - frontend
    volumes:
      - ./database:/var/lib/mysql
    enviroment:
      MYSQL_RANDOM_ROOT_PASSWORD: true

# Do not forget to 'docker network create georgecolgrove' before launch
networks: 
  frontend:
  backend:
